on:
    workflow_dispatch:
    push:
      paths:
        - docs/*
    pull_request:
      branches:
        - docs/*

name: Build and deploy
  
jobs:
    build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        id-token: write
        pages: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Install Python and Dependencies
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
            cache: 'pip'
        - run: python3 -m pip install jupyter
        - run: pip install json-schema-for-humans
        - run: generate-schema-doc --config template_name=md *.json README.md
        - run: generate-schema-doc  *.json index.html 
        - name: Update files
          run: |
            git config --global user.email actions@github.com
            git config --global user.name githubuser
            git add --all --:!docs/*
            git diff-index --quiet HEAD || git commit -m 'Updating the html'
            git push origin master
          
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}